"""
NSE Stock Universe — Nifty 500 + liquid mid/small caps.
All symbols are NSE codes (without .NS suffix).
"""

# ── Sector metadata ────────────────────────────────────────────────────────────
UNIVERSE = {
    # ── Nifty 50 ──────────────────────────────────────────────────────────────
    "RELIANCE":    {"name": "Reliance Industries",        "sector": "Energy / Conglomerate"},
    "TCS":         {"name": "Tata Consultancy Services",  "sector": "IT"},
    "HDFCBANK":    {"name": "HDFC Bank",                  "sector": "Banking"},
    "BHARTIARTL":  {"name": "Bharti Airtel",              "sector": "Telecom"},
    "ICICIBANK":   {"name": "ICICI Bank",                 "sector": "Banking"},
    "INFOSYS":     {"name": "Infosys",                    "sector": "IT"},
    "SBIN":        {"name": "State Bank of India",        "sector": "Banking"},
    "HINDUNILVR":  {"name": "Hindustan Unilever",         "sector": "FMCG"},
    "ITC":         {"name": "ITC",                        "sector": "FMCG"},
    "LT":          {"name": "Larsen & Toubro",            "sector": "Capital Goods"},
    "KOTAKBANK":   {"name": "Kotak Mahindra Bank",        "sector": "Banking"},
    "AXISBANK":    {"name": "Axis Bank",                  "sector": "Banking"},
    "BAJFINANCE":  {"name": "Bajaj Finance",              "sector": "NBFC"},
    "WIPRO":       {"name": "Wipro",                      "sector": "IT"},
    "ASIANPAINT":  {"name": "Asian Paints",               "sector": "Paints"},
    "MARUTI":      {"name": "Maruti Suzuki",              "sector": "Auto"},
    "SUNPHARMA":   {"name": "Sun Pharmaceutical",         "sector": "Pharma"},
    "M&M":         {"name": "Mahindra & Mahindra",        "sector": "Auto"},
    "TITAN":       {"name": "Titan Company",              "sector": "Jewellery"},
    "NTPC":        {"name": "NTPC",                       "sector": "Power"},
    "POWERGRID":   {"name": "Power Grid Corp",            "sector": "Power"},
    "HCLTECH":     {"name": "HCL Technologies",           "sector": "IT"},
    "TECHM":       {"name": "Tech Mahindra",              "sector": "IT"},
    "ULTRACEMCO":  {"name": "UltraTech Cement",           "sector": "Cement"},
    "BAJAJFINSV":  {"name": "Bajaj Finserv",              "sector": "NBFC"},
    "NESTLEIND":   {"name": "Nestle India",               "sector": "FMCG"},
    "TATAMOTORS":  {"name": "Tata Motors",                "sector": "Auto"},
    "ADANIPORTS":  {"name": "Adani Ports",                "sector": "Infrastructure"},
    "COALINDIA":   {"name": "Coal India",                 "sector": "Mining"},
    "TATASTEEL":   {"name": "Tata Steel",                 "sector": "Metals"},
    "GRASIM":      {"name": "Grasim Industries",          "sector": "Cement"},
    "ONGC":        {"name": "ONGC",                       "sector": "Oil & Gas"},
    "DIVISLAB":    {"name": "Divi's Laboratories",        "sector": "Pharma"},
    "DRREDDY":     {"name": "Dr. Reddy's Laboratories",   "sector": "Pharma"},
    "HEROMOTOCO":  {"name": "Hero MotoCorp",              "sector": "Auto"},
    "CIPLA":       {"name": "Cipla",                      "sector": "Pharma"},
    "BPCL":        {"name": "BPCL",                       "sector": "Oil & Gas"},
    "EICHERMOT":   {"name": "Eicher Motors",              "sector": "Auto"},
    "INDUSINDBK":  {"name": "IndusInd Bank",              "sector": "Banking"},
    "JSWSTEEL":    {"name": "JSW Steel",                  "sector": "Metals"},
    "HINDALCO":    {"name": "Hindalco Industries",        "sector": "Metals"},
    "APOLLOHOSP":  {"name": "Apollo Hospitals",           "sector": "Healthcare"},
    "LTIM":        {"name": "LTIMindtree",                "sector": "IT"},
    "BRITANNIA":   {"name": "Britannia Industries",       "sector": "FMCG"},
    "TATACONSUM":  {"name": "Tata Consumer Products",     "sector": "FMCG"},

    # ── Nifty Next 50 ─────────────────────────────────────────────────────────
    "DMART":       {"name": "Avenue Supermarts",          "sector": "Retail"},
    "HAL":         {"name": "Hindustan Aeronautics",      "sector": "Defence"},
    "PIDILITIND":  {"name": "Pidilite Industries",        "sector": "Chemicals"},
    "SIEMENS":     {"name": "Siemens India",              "sector": "Capital Goods"},
    "DABUR":       {"name": "Dabur India",                "sector": "FMCG"},
    "GODREJCP":    {"name": "Godrej Consumer Products",   "sector": "FMCG"},
    "BERGEPAINT":  {"name": "Berger Paints",              "sector": "Paints"},
    "MARICO":      {"name": "Marico",                     "sector": "FMCG"},
    "TORNTPHARM":  {"name": "Torrent Pharmaceuticals",    "sector": "Pharma"},
    "HDFCLIFE":    {"name": "HDFC Life Insurance",        "sector": "Insurance"},
    "ICICIPRULI":  {"name": "ICICI Prudential Life",      "sector": "Insurance"},
    "SBILIFE":     {"name": "SBI Life Insurance",         "sector": "Insurance"},
    "AMBUJACEM":   {"name": "Ambuja Cements",             "sector": "Cement"},
    "AUROPHARMA":  {"name": "Aurobindo Pharma",           "sector": "Pharma"},
    "MUTHOOTFIN":  {"name": "Muthoot Finance",            "sector": "NBFC"},
    "CHOLAFIN":    {"name": "Cholamandalam Finance",      "sector": "NBFC"},
    "LUPIN":       {"name": "Lupin",                      "sector": "Pharma"},
    "PGHH":        {"name": "P&G Hygiene",                "sector": "FMCG"},
    "INDHOTEL":    {"name": "Indian Hotels (Taj)",        "sector": "Hospitality"},
    "BOSCHLTD":    {"name": "Bosch India",                "sector": "Auto Ancillary"},
    "BHEL":        {"name": "BHEL",                       "sector": "Capital Goods"},
    "GAIL":        {"name": "GAIL India",                 "sector": "Oil & Gas"},
    "IOC":         {"name": "Indian Oil Corporation",     "sector": "Oil & Gas"},
    "ABB":         {"name": "ABB India",                  "sector": "Capital Goods"},
    "IRFC":        {"name": "IRFC",                       "sector": "NBFC"},

    # ── Midcap Liquid ──────────────────────────────────────────────────────────
    "NAUKRI":      {"name": "Info Edge (Naukri)",         "sector": "Internet"},
    "PERSISTENT":  {"name": "Persistent Systems",         "sector": "IT"},
    "COFORGE":     {"name": "Coforge",                    "sector": "IT"},
    "MPHASIS":     {"name": "Mphasis",                    "sector": "IT"},
    "IRCTC":       {"name": "IRCTC",                      "sector": "Travel"},
    "CONCOR":      {"name": "Container Corporation",      "sector": "Logistics"},
    "PAGEIND":     {"name": "Page Industries",            "sector": "Textile"},
    "POLYCAB":     {"name": "Polycab India",              "sector": "Electricals"},
    "HDFCAMC":     {"name": "HDFC AMC",                   "sector": "Asset Management"},
    "KPITTECH":    {"name": "KPIT Technologies",          "sector": "IT"},
    "LTTS":        {"name": "L&T Technology Services",    "sector": "IT"},
    "TIINDIA":     {"name": "Tube Investments",           "sector": "Auto Ancillary"},
    "ASHOKLEY":    {"name": "Ashok Leyland",              "sector": "Auto"},
    "BALKRISIND":  {"name": "Balkrishna Industries",      "sector": "Tyres"},
    "CANBK":       {"name": "Canara Bank",                "sector": "Banking"},
    "BANKBARODA":  {"name": "Bank of Baroda",             "sector": "Banking"},
    "FEDERALBNK":  {"name": "Federal Bank",               "sector": "Banking"},
    "IDFCFIRSTB":  {"name": "IDFC First Bank",            "sector": "Banking"},
    "JUBLFOOD":    {"name": "Jubilant FoodWorks",         "sector": "QSR"},
    "TATACOMM":    {"name": "Tata Communications",        "sector": "Telecom"},
    "TRENT":       {"name": "Trent (Westside/Zudio)",     "sector": "Retail"},
    "ZOMATO":      {"name": "Zomato",                     "sector": "Food Tech"},
    "VEDL":        {"name": "Vedanta",                    "sector": "Metals"},
    "TATAPOWER":   {"name": "Tata Power",                 "sector": "Power"},
    "ADANIGREEN":  {"name": "Adani Green Energy",         "sector": "Renewable Energy"},
    "PFC":         {"name": "Power Finance Corporation",  "sector": "NBFC"},
    "RECLTD":      {"name": "REC Limited",                "sector": "NBFC"},
    "RVNL":        {"name": "Rail Vikas Nigam",           "sector": "Infrastructure"},
    "NHPC":        {"name": "NHPC",                       "sector": "Power"},
    "SJVN":        {"name": "SJVN",                       "sector": "Power"},
    "APLAPOLLO":   {"name": "APL Apollo Tubes",           "sector": "Steel"},
    "MOTHERSON":   {"name": "Samvardhana Motherson",      "sector": "Auto Ancillary"},
    "ATGL":        {"name": "Adani Total Gas",            "sector": "Gas"},
    "HONAUT":      {"name": "Honeywell Automation",       "sector": "Capital Goods"},
    "VOLTAS":      {"name": "Voltas",                     "sector": "Consumer Durables"},
    "HAVELLS":     {"name": "Havells India",              "sector": "Electricals"},
    "DIXON":       {"name": "Dixon Technologies",         "sector": "Electronics"},
    "ASTRAL":      {"name": "Astral",                     "sector": "Pipes & Fittings"},
    "SUPREMEIND":  {"name": "Supreme Industries",         "sector": "Plastics"},
    "THERMAX":     {"name": "Thermax",                    "sector": "Capital Goods"},
    "SCHAEFFLER":  {"name": "Schaeffler India",           "sector": "Auto Ancillary"},
    "SOLARINDS":   {"name": "Solar Industries",           "sector": "Defence / Chemicals"},
    "KALYANKJIL":  {"name": "Kalyan Jewellers",           "sector": "Jewellery"},
    "CARBORUNIV":  {"name": "Carborundum Universal",      "sector": "Abrasives"},
    "DEEPAKNTR":   {"name": "Deepak Nitrite",             "sector": "Chemicals"},
    "GNFC":        {"name": "GNFC",                       "sector": "Chemicals"},
    "NAVINFLUOR":  {"name": "Navin Fluorine",             "sector": "Chemicals"},
    "PIIND":       {"name": "PI Industries",              "sector": "Agrochemicals"},
    "UPL":         {"name": "UPL",                        "sector": "Agrochemicals"},
    "GODREJPROP":  {"name": "Godrej Properties",          "sector": "Real Estate"},
    "PRESTIGE":    {"name": "Prestige Estates",           "sector": "Real Estate"},
    "OBEROIRLTY":  {"name": "Oberoi Realty",              "sector": "Real Estate"},
    "MFSL":        {"name": "Max Financial Services",     "sector": "Insurance"},
    "STARHEALTH":  {"name": "Star Health Insurance",      "sector": "Insurance"},
    "CDSL":        {"name": "CDSL",                       "sector": "Financial Services"},
    "MCX":         {"name": "MCX India",                  "sector": "Exchange"},
    "BSE":         {"name": "BSE Ltd",                    "sector": "Exchange"},
    "ANGELONE":    {"name": "Angel One",                  "sector": "Broking"},
    "360ONE":      {"name": "360 One WAM",                "sector": "Wealth Management"},
    "CAMS":        {"name": "CAMS",                       "sector": "Financial Services"},
    "SUNDARMFIN":  {"name": "Sundaram Finance",           "sector": "NBFC"},
    "BAJAJHFL":    {"name": "Bajaj Housing Finance",      "sector": "Housing Finance"},
    "LICI":        {"name": "LIC of India",               "sector": "Insurance"},
    "YESBANK":     {"name": "Yes Bank",                   "sector": "Banking"},
    "BANDHANBNK":  {"name": "Bandhan Bank",               "sector": "Banking"},
    "RBLBANK":     {"name": "RBL Bank",                   "sector": "Banking"},
    "KAJAARIA":    {"name": "Kajaria Ceramics",           "sector": "Building Materials"},
    "CERA":        {"name": "Cera Sanitaryware",          "sector": "Building Materials"},
    "WHIRLPOOL":   {"name": "Whirlpool of India",         "sector": "Consumer Durables"},
    "CROMPTON":    {"name": "Crompton Greaves Consumer",  "sector": "Consumer Durables"},
    "VBL":         {"name": "Varun Beverages",            "sector": "Beverages"},
    "UNITDSPR":    {"name": "United Spirits",             "sector": "Beverages"},
    "RADICO":      {"name": "Radico Khaitan",             "sector": "Beverages"},
    "FORTIS":      {"name": "Fortis Healthcare",          "sector": "Healthcare"},
    "MAXHEALTH":   {"name": "Max Healthcare",             "sector": "Healthcare"},
    "METROPOLIS":  {"name": "Metropolis Healthcare",      "sector": "Healthcare"},
    "LALPATHLAB":  {"name": "Dr Lal PathLabs",            "sector": "Healthcare"},
    "KIMS":        {"name": "Krishna Institute of Med.",  "sector": "Healthcare"},
}


def get_symbols() -> list:
    return list(UNIVERSE.keys())


def get_meta(symbol: str) -> dict:
    return UNIVERSE.get(symbol, {"name": symbol, "sector": "Unknown"})
