@echo off
REM Stock Analyzer — daily screener run
REM Auto-generated by setup_daily_schedule.py

cd /d "D:\Gagan\Projects\stock-analyzer"

REM Rotate log if > 5 MB
for %%A in ("D:\Gagan\Projects\stock-analyzer\logs\daily_run.log") do if %%~zA gtr 5242880 (
    move /y "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log" "D:\Gagan\Projects\stock-analyzer\logs\daily_run_prev.log" >nul 2>&1
)

echo. >> "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log"
echo ============================================================ >> "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log"
echo Run started: %DATE% %TIME% >> "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log"
echo ============================================================ >> "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log"

"C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe" run_screener.py --no-open >> "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log" 2>&1

echo Run finished: %DATE% %TIME% >> "D:\Gagan\Projects\stock-analyzer\logs\daily_run.log"
