"""
One-time setup: registers a Windows Task Scheduler job that runs the
stock screener every weekday (Mon–Fri) at 4:15 PM IST (after market close).

Run this script ONCE from your project directory:
    python scripts/setup_daily_schedule.py

After that, everything is fully automatic:
  - Screener runs daily
  - Predictions + outcomes are saved to PostgreSQL
  - Logs written to logs/daily_run.log
  - Log file rotated when it exceeds 5 MB

To verify the task was created:
    Open Task Scheduler → Task Scheduler Library → StockAnalyzerDaily

To remove the task:
    schtasks /delete /tn StockAnalyzerDaily /f
"""

import os
import subprocess
import sys
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────

PROJECT_DIR = Path(__file__).parent.parent.resolve()
PYTHON      = sys.executable
SCRIPTS_DIR = PROJECT_DIR / "scripts"
LOG_DIR     = PROJECT_DIR / "logs"
BAT_FILE    = SCRIPTS_DIR / "run_daily.bat"
LOG_FILE    = LOG_DIR / "daily_run.log"
TASK_NAME   = "StockAnalyzerDaily"
RUN_TIME    = "16:15"   # 4:15 PM — 45 min after NSE close (3:30 PM)


# ── Create directories ─────────────────────────────────────────────────────────

LOG_DIR.mkdir(exist_ok=True)
SCRIPTS_DIR.mkdir(exist_ok=True)


# ── Write the batch file ───────────────────────────────────────────────────────

bat_lines = f"""@echo off
REM Stock Analyzer — daily screener run
REM Auto-generated by setup_daily_schedule.py

cd /d "{PROJECT_DIR}"

REM Rotate log if > 5 MB
for %%A in ("{LOG_FILE}") do if %%~zA gtr 5242880 (
    move /y "{LOG_FILE}" "{LOG_DIR}\\daily_run_prev.log" >nul 2>&1
)

echo. >> "{LOG_FILE}"
echo ============================================================ >> "{LOG_FILE}"
echo Run started: %DATE% %TIME% >> "{LOG_FILE}"
echo ============================================================ >> "{LOG_FILE}"

"{PYTHON}" run_screener.py --no-open >> "{LOG_FILE}" 2>&1

echo Run finished: %DATE% %TIME% >> "{LOG_FILE}"
"""

BAT_FILE.write_text(bat_lines, encoding="utf-8")
print(f"[OK] Batch file created: {BAT_FILE}")


# ── Register Windows Task Scheduler job ───────────────────────────────────────

cmd = [
    "schtasks", "/create",
    "/tn",  TASK_NAME,
    "/tr",  str(BAT_FILE),
    "/sc",  "weekly",
    "/d",   "MON,TUE,WED,THU,FRI",    # weekdays only
    "/st",  RUN_TIME,
    "/rl",  "HIGHEST",                 # run with highest privileges
    "/f",                              # overwrite if already exists
]

print(f"\nRegistering task '{TASK_NAME}' (weekdays at {RUN_TIME})…")
result = subprocess.run(cmd, capture_output=True, text=True)

if result.returncode == 0:
    print(f"[OK] Task scheduled successfully.")
    print(f"\n  Schedule : Mon–Fri at {RUN_TIME}")
    print(f"  Script   : {BAT_FILE}")
    print(f"  Log file : {LOG_FILE}")
    print(f"\nTo verify → open Task Scheduler and look for '{TASK_NAME}'")
    print("To run now → right-click the task → Run")
else:
    print(f"[ERROR] schtasks failed:\n{result.stderr.strip()}")
    print("\nTry running this script as Administrator:")
    print("  Right-click terminal → Run as Administrator → python scripts/setup_daily_schedule.py")
    sys.exit(1)


# ── Quick DB connectivity check ────────────────────────────────────────────────

print("\nChecking database connection…")
try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_DIR / ".env")
    from screener.db import is_available, init_schema
    if is_available():
        ok = init_schema()
        if ok:
            print("[OK] Connected to PostgreSQL — schema ready.")
        else:
            print("[WARN] Connected but schema init failed. Check DB logs.")
    else:
        print("[WARN] DATABASE_URL not set or psycopg2 not installed.")
        print("       Install: pip install psycopg2-binary")
        print("       Then add DATABASE_URL to your .env file.")
except Exception as e:
    print(f"[WARN] DB check failed: {e}")

print("\nSetup complete. The screener will run automatically every weekday.")
